lib/active_merchant/billing/gateways/braintree_blue.rb

We were trying to use the uninitialized `Braintree::PaypalAccount` class here which was resulting in a `Braintree::ConfigurationError`. Instead, we update to use `braintree_gateway`, which is pre-configured in the constructor.

[bugfix] Uses the correct method to delete existing paypal accounts

---

lib/active_merchant/billing/gateways/fusebox.rb
test/unit/gateways/fusebox_test.rb

It appears that not all banks support the $0 auth, even though the fusebox documentation recommends it as the way to store a card.
This switches from a $0 auth to a $1 auth in an attempt at a more reliable way to store cards.  Note that Visa mandates warn that there may be fees for "Authorization System Misuse", but since support for $0 seems to still be problematic, we don't feel these fees will ever materialize.

[fusebox] Switch store from $0 auth to $1 auth

---

lib/active_merchant/billing/gateways/quickpay/quickpay_v4to7.rb

This removes the condition `if @protocol >= 7` so the amount and the currency will be sent to `:subscribe` requests made over the v3 protocol.
The reason for this is a change on the part of Quickpay now requiring this information to be present.

Always send amount and currency to Quickpay store card

---

lib/active_merchant/billing/gateways/quickpay/quickpay_common.rb

The latest PR (https://github.com/chargify/active_merchant/pull/39) added amount and currency to `:subscribe` requests. That caused a new error due to MD5 checks not including these fields. This PR fixes this.

Add amount and currency to md5 check fields

---

lib/active_merchant/billing/gateways/litle.rb

According to the Litle gateway FAQ, we should be including the expiration date when making a purchase using a token.
The field is not required, but it is recommended and should improve acceptance rates.
Fixes https://github.com/activemerchant/active_merchant/issues/2273

Litle: include expiration date with token

---

lib/active_merchant/billing/gateways/litle.rb

Allows the billing address to be sent to Vantiv/Litle along with the string token. Also adds in the name and email address.

Allow billing address to be sent with token.

---

lib/active_merchant/billing/gateways/braintree_blue.rb

This passes along `device_data` to Braintree for Customer Create
https://developers.braintreepayments.com/reference/request/customer/create/ruby#device_data
and Customer Update
https://developers.braintreepayments.com/reference/request/customer/create/ruby#device_data

[braintree] Pass device_data in customer create/update

---

lib/active_merchant/billing/gateways/nmi.rb
test/unit/gateways/nmi_test.rb

In a communication with NMI:
> In order to meet the criteria of "CVV Required on First Transaction," you would need to run a Validate (0.00 auth essentially) or an Authorization prior to adding the card to the Customer Vault, or (if you are able) a hybrid transaction where you run a Validate or Authorization WITH an Add Customer Action. Running a Sale would work as well.
This change runs the `#validate` at the beginning of `#store`.
Following the pattern of other tests with multiple calls, we just test the success of the response, not the request.

NMI: Verify on store for CVV check on First Transaction.

---

lib/active_merchant/billing/gateways/litle.rb

Vantiv, which now owns Litle, is rebranding the Litle API. This includes
changing the endpoint urls. The new live endpoint url is already active.
Replacement for the Sandbox test environment url is forthcoming. The
deadline for this change is August 31 2017, when the previous live url
will no longer function.
Unit:
32 tests, 137 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Remote:
28 tests, 117 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
Closes #2531

Litle: Update urls and name to Vantiv

---

lib/active_merchant/billing/gateways/cyber_source.rb
test/unit/gateways/cyber_source_test.rb

CyberSource sometimes sends a response that has reason_code 100 (meaning Successful transaction) but the overall decision was REJECT.
It is confusing to see a success message alongside a failure, so in this one case, we will override the translation for the code.

CyberSource: Translate REJECT with reason_code 100 as Failure

---

lib/active_merchant/billing/gateways/litle.rb

Previously the URL for live transactions was updated, however the test url wasn't.
This updates the sandbox url based on the documentation in  https://developer.vantiv.com/docs/DOC-1375

Vantiv (Litle): Update sandbox url for testing

---

lib/active_merchant/billing/gateways/nmi.rb
test/unit/gateways/nmi_test.rb

This reverts commit 34a922bcc3f7c13a02eca297eb555f48af0b77a9.
This is part of the fix for https://github.com/chargify/chargify/issues/9171
The goal is to allow merchants to bypass the authorization request, but because the ActiveMerchant code was hard-coded to always verify, this revert commit will allow us to handle auth and store within Conduit.
This PR should not be merged until the Chargify and Conduit changes to the NMI gateway code have also been merged.
See https://github.com/chargify/chargify/pull/9240
See https://github.com/chargify/conduit/pull/145

Revert "NMI: Verify on store for CVV check on First Transaction."

---

lib/active_merchant/billing/gateways/litle.rb

Vantiv (Litle) has an open sandbox for testing, however merchants need to use the pre-live environment to show that their integration works.
Since the sandbox does not require credentials, use the sandbox url if credentials are missing, and the pre-live environment if credentials are provided.

Vantiv: Support for pre-live environment

---

lib/active_merchant/billing/gateways/cyber_source.rb
test/remote/gateways/remote_cyber_source_test.rb
test/unit/gateways/cyber_source_test.rb

It was noticed that the cybersource gateway was interpreting all transactions as stored credit cards, when it was possible to encounter stored ACH payment sources.
This change simply passes in what kind of transaction it is, 'check' or 'credit_card', whenever a tokenized operation is performed (Because if all you have is a token, you cant tell what kind of operation it is).  This information is included in the options hash under the key  ```:source_type```.     
The stubbed xml responses for store and purchase where taken directly from the chargify store and purchase raw gateway logs.  
The soapfault message change was done to fix a broken test, not sure how long it has been broken, but its not related at all to this change.
There is a remote tax test that fails, but this appears to be …

Cybersource:  Adds ability to have stored ACH purchases.

---

lib/active_merchant/billing/gateways/go_cardless.rb

This add phone_number to customer attributes (this is required for New Zealand).

[feature] GoCardless: add phone_number to customer attributes

---

lib/active_merchant/billing/gateways/go_cardless.rb

It adds `danish_identity_number` and `swedish_identity_number` to customer attributes (these are required for Sweden and New Zealand GoCardless schemes).

GoCardless: add danish_identity_number and swedish_identity_number to customer attributes

---

lib/active_merchant/billing/gateways/nmi.rb
lib/active_merchant/network_connection_retries.rb
test/remote/gateways/remote_nmi_test.rb
test/unit/gateways/nmi_test.rb

**User Story:** As a merchant, I would like to be able to send all of the details, fields, & data required by Visa & Mastercard to be compliant and avoid high transaction failure rates.
Using this commit https://github.com/activemerchant/active_merchant/commit/b12da5a8b1737f91b8f570512582c1f79904922f as the introduction to the normalized stored credential options, I have added NMI specific fields to the request.
```
The hash takes the following structure:
{
stored_credential: {
inital_transaction: Boolean, # either true or false
recurring: Boolean, # either true or false
initiator: String, # either "merchant" or "cardholder"
network_transaction_id: String # returned card network transaction id
}
}
```
[NMI Docs](https://secure.networkmerchants.com/gw/merchants/resources/integration/integra …

[internal] Adds NMI Stored Credentials support

---

lib/active_merchant/billing/gateways/quickpay/quickpay_v4to7.rb
test/unit/gateways/quickpay_v4to7_test.rb

This removes the condition `if @protocol >= 7` so the amount and the currency will be sent to `:subscribe` requests made over the v3 protocol.
The reason for this is a change on the part of Quickpay now requiring this information to be present.
This change was implemented previously: https://github.com/chargify/active_merchant/pull/39 but was inadvertently reverted in https://github.com/chargify/active_merchant/pull/64 -- this PR is adding the change back in this time with test updates to ensure the change remains.

Quickpay: Always send currency and amount to Quickpay on store card

---

lib/active_merchant/billing/gateways/braintree_blue.rb
test/remote/gateways/remote_braintree_blue_test.rb
test/remote/gateways/remote_braintree_orange_test.rb
test/unit/gateways/braintree_blue_test.rb

This is simply adding support to :three_d_secure_pass_thru params for
Braintree, documented here: https://developers.braintreepayments.com/reference/request/transaction/sale/ruby#three_d_secure_pass_thru

Add 3D secure (cherry pick 48440c)

---

lib/active_merchant/billing/gateways/cyber_source.rb
lib/active_merchant/country.rb
test/remote/gateways/remote_cyber_source_test.rb
test/schema/cyber_source/CyberSourceTransaction_1.153.xsd
test/unit/gateways/cyber_source_test.rb

Implements ActiveMerchant part of https://trello.com/c/hJh5hz6j/414-cybersource-stored-credentials
* cherry picks some of the original Active Merchant fork Stored Credentials changes
* adapts to the changes to JPY that were introduced in the original Active Merchant fork
* adds Stored Credentials support to the `#purchase` method
* Adds a test for actually receiving a network transaction id
After this PR is merged, it should be released under a new tag and referenced in the corresponding [Conduit](https://github.com/chargify/conduit/pull/211) and [Chargify](https://github.com/chargify/chargify/pull/12822) changes

CyberSource Stored Credentials Support

---

lib/active_merchant/billing/gateways/stripe.rb
test/unit/gateways/stripe_test.rb

This add support for Stripe payment intents API that is required for 3D secure.
No changes in remote tests, because they are already failing for Stripe, also we have tests in Conduit and in Chargify.
Co-authored-by: Zbigniew Humeniuk <zbigniew@chargify.com>

Stripe payment intents API (3D Secure)

---

lib/active_merchant/billing/gateways/braintree_blue.rb
test/remote/gateways/remote_braintree_blue_test.rb
test/unit/gateways/braintree_blue_test.rb

Cherry Pick from the original Active Merchant.
This change adds ability to pass transaction_source parameter to BrainTree gateway.
Braintree is storing stored_credential on their side, but we need to pass transaction_source parameter with request.

Braintree: Adds support for transaction_source

---

lib/active_merchant/billing/gateways/cyber_source.rb
test/remote/gateways/remote_cyber_source_test.rb
test/unit/gateways/cyber_source_test.rb

This PR adds support for sending `authenticationTransactionID` and `referenceID` to the CyberSource which are used in 3DS 2.x flow.

[feature] Add 3D Secure 2.x support to CyberSource

---

lib/active_merchant/billing/gateways/cyber_source.rb
test/unit/gateways/cyber_source_test.rb

When sending partial card details to Cybersource, an account number is
not required. The presence of the `accountNumber` element in the request
forces validation, and so a "Invalid account number. (231)" response
will be given when the account number is not provided, even though it is
optional for update.
This change ensures that the `<accountNumber/>` element is only included
in the request if there is a card number provided.

Cybersource: Allow partial update of credit card

---

lib/active_merchant/billing/gateways/payment_express.rb

Adds `test_url` to `PaymentExpressGateway`, based on
https://github.com/activemerchant/active_merchant/commit/3d0e832bf76561a4d72c67149da02f69966fed34.

Add test_url to PaymentExpressGateway

---

lib/active_merchant/billing/gateways/braintree_blue.rb
test/remote/gateways/remote_braintree_blue_test.rb

This change is needed for Braintree 3DS auth on SSP to work.
Related task: https://trello.com/c/52kfMc6T/553-braintree-ssp-3ds-store-authorizations

Braintree 3ds ssp

---

lib/active_merchant/billing/gateways/stripe.rb

When only the customer id is available and a payment method is needed, we should use the customer's default payment source.

Stripe: Use customer's default source for charges

---

lib/active_merchant/billing/gateways/braintree_blue.rb
test/remote/gateways/remote_braintree_blue_test.rb

This PR changes `three_d_secure_info` name to `check_payment_method_nonce` and uses `Response`s as results.

[change] Change three_d_secure_info to check_payment_method_nonce

---

lib/active_merchant/billing/gateways/braintree_blue.rb

During `purchase` action `payment_method_nonce` was overwritten by `credit_card_or_vault_id `. I don't have history knowledge of that decision but in order to validate SCA, I need to pass original`payment_method_nonce` to Braintree.
https://github.com/activemerchant/active_merchant/commit/c15a58a9bc866f9442b4b5d797d1f2aafc01dd0b
https://developers.braintreepayments.com/reference/request/transaction/sale/ruby

Braintree: Pass payment_method_nonce if present during purchase

---

lib/active_merchant/billing/gateways/payment_express.rb
test/unit/gateways/payment_express_test.rb

This change updates PaymentExpress scrub method to filter `PostPassword` and changes `supports_scrubbing` method to `supports_scrubbing?` like it is in most of other gateways.

PaymentExpress: update scrubbing

---

lib/active_merchant/billing/gateways/quickpay/quickpay_v4to7.rb

According to Quickpay support, the testmode flag is no longer supported on the old platform.
See https://github.com/activemerchant/active_merchant/pull/3367

Quickpay: Remove testmode flag from v4-v7 platform

---

lib/active_merchant/billing/gateways/stripe.rb
test/unit/gateways/stripe_test.rb

This PR fix bug in Stripe when customer has only payment method and no default source.
Trello card: https://trello.com/c/g9juTN5o/638-unplanned-stripe-search-for-payment-method-to-charge-for-fitbit

Stripe: fix bug when only payment methods are present on customer

---

lib/active_merchant/billing/gateways/stripe.rb
test/unit/gateways/stripe_test.rb

This will throws an exception in case when payment methods api for customer returns an error.
It occurred on production that client can remove customer from Stripe, and when that happens payment methods API for customer will returns error instead of proper response.

Stripe: throws an exception when payment methods for customer returns error

---

lib/active_merchant/billing/gateways/stripe.rb
test/unit/gateways/stripe_test.rb

This adds suport for Stripe's scenario when customer has default_source sets as source (src_)

Stripe: add support for customer default source sets as source

---

lib/active_merchant/billing/gateways/stripe.rb
test/unit/gateways/stripe_test.rb

Currently we are checking the payment intent status and retrying a
payment if the status comes back as "requries_source" this leaves a lot
of room for interpretation and also causes us to retry payments that
shouldn't be retried. By checking the last payment error decline code we
are ensuring that we are only retrying when the payment fails for 3D
Secure

Check last payment error decline code for Stripe retry

---

lib/active_merchant/billing/gateways/paymill.rb
test/remote/gateways/remote_paymill_test.rb

[JIRA - PGT-65](https://chargify.atlassian.net/jira/software/projects/PGT/boards/32?selectedIssue=PGT-65)
Dependency of https://github.com/chargify/conduit/pull/252
Dependency of https://github.com/chargify/chargify/pull/15282
We should remove all traces of the Paymill gateway from our codebase since it's not being used or offered anymore 🔥🔥🔥
I did some git sleuthing[1] to try to determine what changes we had made to our ActiveMerchant fork related to Paymill and I found [this commit](https://github.com/chargify/active_merchant/commit/bbeee0b0a06ad91c39bf7595264d6af1c0d82974). This PR reverts it since Paymill has been deleted from Chargify and Conduit and there's no reason to deviate from the main ActiveMerchant branch.
[1]:
```
pedrocoronel:~/code/active_merchant [master|⚑ 1] $ git …
```

[internal] Revert Paymill-specific changes

---

activemerchant.gemspec

Necessary for Rails 5.2 compatibility. There were no braking changes since 5.0.0.

Increase ActiveSupport dependency version up to 5.2

---

lib/active_merchant/billing/gateways/braintree_blue.rb

Enables updating apple pay card on Braintree customer to a new one.
The `customer.paypal_accounts.each { |pp| @braintree_gateway.paypal_account.delete(pp.token) }` method has not been tested in neither this fork nor master. The method added in this PR is tested via Chargify tests.

[feature] enable updates for apple pay cards

---

lib/active_merchant/billing/gateways/adyen_checkout.rb
test/fixtures.yml
test/remote/gateways/remote_adyen_checkout_test.rb
test/unit/gateways/adyen_checkout_test.rb

This PR implements the new checkout API that Adyen is encouraging everyone to migrate to. This implementation was made specifically with tokenizing cards in mind:
https://docs.adyen.com/checkout/tokenization/create-and-use-tokens
However the purchase method still supports one-off card purchases if full credit card details are passed.  
Unit Tests:
```
13 tests, 67 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
```
Remote Tests:
```
18 tests, 50 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
```

Adyen Checkout

---

lib/active_merchant/billing/gateways/moneris.rb
test/remote/gateways/remote_moneris_test.rb
test/test_helper.rb
test/unit/gateways/moneris_test.rb

**Why:**
There is a new mandate that is coming into effect on April 2020. It is called Credential on File . What this mandate requires is that merchants who transact using stored cards need to send additional fields ( cof object) to indicate if the card is being stored and whether it is an initial transaction or subsequent transaction
**What:**
Copied support for Credential on File from upstream ActiveMerchant.

Stored Credential for Moneris - Credential on File - PGT-63

---

lib/active_merchant/billing/gateways/stripe.rb

Adds support for the statement_descriptor_suffix attribute when charging a card.
This is present in upstream active_merchant master: 
https://github.com/activemerchant/active_merchant/blob/eb37012ffbb6a374605be21a48e1bab688aa4056/lib/active_merchant/billing/gateways/stripe.rb#L365
It was added in this commit: https://github.com/activemerchant/active_merchant/commit/3b1fdadbb7a3240790086016c719bc8696773a98

Stripe: add support for statement_descriptor_suffix

---

lib/active_merchant/billing/gateways/braintree_blue.rb

**Summary for requirement:**
Merchants must add a descriptor that indicates a transaction related to a trial offer to the first transaction processed after the trial offer ends. This descriptor should be added to the Merchant Name field of the Clearing Record and should include language like “trial,” “trial period,” “free trial,” and the like. This will then appear on bank statements, banking apps, and text alerts that the cardholder sees.
**What is the enhanced descriptor for? Where is it required? ([Visa](https://usa.visa.com/dam/VCOM/global/support-legal/documents/subscription-policy-vbn-visa-public.pdf))**
The enhanced descriptor (e.g., “trial,” “trial period,” “free trial”) is to be included in the Merchant Name field of the clearing record for the first transaction at the end of a …

Statement Descriptor - Braintree

---

lib/active_merchant/billing/gateways/braintree_blue.rb

ruby does not support `.as_json`
move `descriptor params` to `transaction_hash` method

Statement Descriptor - Braintree - fix .as_json bug

---

lib/active_merchant/billing/gateways/cyber_source.rb
test/remote/gateways/remote_cyber_source_test.rb
test/unit/gateways/cyber_source_test.rb

**Summary for requirement:**
Merchants must add a descriptor that indicates a transaction related to a trial offer to the first transaction processed after the trial offer ends. This descriptor should be added to the Merchant Name field of the Clearing Record and should include language like “trial,” “trial period,” “free trial,” and the like. This will then appear on bank statements, banking apps, and text alerts that the cardholder sees.
**What is the enhanced descriptor for? Where is it required? ([Visa](https://usa.visa.com/dam/VCOM/global/support-legal/documents/subscription-policy-vbn-visa-public.pdf))**
The enhanced descriptor (e.g., “trial,” “trial period,” “free trial”) is to be included in the Merchant Name field of the clearing record for the first transaction at the end of a …

Cybersource Statement Descriptor

---

lib/active_merchant/billing/gateways/adyen_checkout.rb

**Summary for requirement:**
Merchants must add a descriptor that indicates a transaction related to a trial offer to the first transaction processed after the trial offer ends. This descriptor should be added to the Merchant Name field of the Clearing Record and should include language like “trial,” “trial period,” “free trial,” and the like. This will then appear on bank statements, banking apps, and text alerts that the cardholder sees.
**What is the enhanced descriptor for? Where is it required? ([Visa](https://usa.visa.com/dam/VCOM/global/support-legal/documents/subscription-policy-vbn-visa-public.pdf))**
The enhanced descriptor (e.g., “trial,” “trial period,” “free trial”) is to be included in the Merchant Name field of the clearing record for the first transaction at the end of a …

[Visa][Statement Descriptor] - Adyen

---

lib/active_merchant/billing/gateways/forte.rb

This PR:
- Uses `URI.join` to safely form URLs
- Gets rid of `add_auth` since we're using a base URL that contains org + location info
- ~~Replaces `raw_ssl_request` with `ssl_request` which allows us to get rid of overriding `handle_resp`~~ (didn't work)
- ~~Splits the HTTP-specific part of `commit` into a separate method~~ (didn't work either)
- Fixes most Rubocop warnings

Refactor and fix Rubocop warnings

---

lib/active_merchant/billing/gateways/forte.rb
test/remote/gateways/remote_forte_test.rb

Previously, the unstore method only deleted the entire customer.
Since Forte allows multiple cards per customer, this commit allows users to specify either a customer id, which deletes the entire customer, or both a customer and card id, in which case only the card will be deleted.

Implement unstore for card only

---

lib/active_merchant/billing/gateways/forte.rb
test/remote/gateways/remote_forte_test.rb

Allows passing in the sec_code attribute and defaults to WEB if one is not provided
See https://www.forte.net/devdocs/api_resources/forte_api_v2.htm#echeck
The attribute has been made required in the sandbox in advance of requiring it in production later this year.
Taken from public PR activemerchant/active_merchant 3640

Forte: add sec_code attribute for echeck

---

lib/active_merchant/billing/gateways/forte.rb
test/unit/gateways/forte_test.rb

- update test with new commit method signature
- check that url is not already a URI before parsing

Forte: fix unit test failures

---

lib/active_merchant/billing/gateways/forte.rb
test/remote/gateways/remote_forte_test.rb

If customer and/or paymethod tokens are being used, then require sec_code to be set in the options.
We cannot tell whether the paymethod token is for a credit card or a bank account, so we cannot provide a default in this case.
Also extracts logic to split the token on the pipe symbol into a separate method.

Forte: only default sec_code when bank account details are present

---

lib/active_merchant/billing/gateways/authorize_net_cim.rb
test/unit/gateways/authorize_net_cim_test.rb

Authorize.net can send back one or multiple errors in their responses.
We need to correctly assess whether response["messages"]["message"] is
an Array or Hash, and if it is an Array, then we need to set the top
level error_code and message fields to the first error returned.
Related issue: https://github.com/activemerchant/active_merchant/issues/2244
Without this fix, we have seen some `TypeError` exceptions similar to the above issue:
```
TypeError: no implicit conversion of String into Integer
```

Authorize.net CIM - Handle multiple error messages

---

lib/active_merchant/billing/gateways/forte.rb
test/remote/gateways/remote_forte_test.rb

This allows "partial updates" of payment methods (and customers) without supplying the full card number or bank account number.  For example, the name, billing address and expiration date can be updated.
Co-authored-by: Marcelo De Polli <marcelo.polli@gmail.com>

Forte: ability to update payment method without account number

---

lib/active_merchant/billing/gateways/cyber_source.rb

https://chargify.atlassian.net/browse/PGT-77
Problem with second address field update for Cybersource.
If a customer removes the second address field ActiveMerchand doesn't send this field and this field doesn't update.
In code, the second address is `street2`
_source ActiveMerchant lib/active_merchant/billing/gateways/cyber_source.rb_:
```ruby
def add_address(xml, payment_method, address, options, shipTo = false)
xml.tag! shipTo ? 'shipTo' : 'billTo' do
xml.tag! 'firstName',             payment_method.first_name             if payment_method
xml.tag! 'lastName',              payment_method.last_name              if payment_method
xml.tag! 'street1',               address[:address1]
xml.tag! 'street2',               address[:address2]                unless address[:address2].blank?
[...] …
```

[bugfix] cybersource - update street2 address

---

lib/active_merchant/billing/gateways/authorize_net_cim.rb
test/unit/gateways/authorize_net_cim_test.rb

AuthorizeNet sometimes responds with an HTML error page, which cannot be parsed as XML.
If the parsed response is blank, (it will be nil,) then return early with an error.
Continuing and trying to access elements in the non-existent hash currently causes errors.

AuthorizeNet: Return error if response cannot be parsed

---

lib/active_merchant/billing/gateways/blue_snap.rb

This will migrate making purchases to use subscriptions API.
Because after some discussion with BlueSnap support they told us, that we need to use this API instead of the old one

Migrate purchase to use subscriptions API

---

lib/active_merchant/billing/gateways/braintree_blue.rb
test/remote/gateways/remote_braintree_blue_test.rb
test/test_helper.rb

This PR will allow partial updates for PayPal accounts with BraintreeBlue.
Partial update will happen if no `payment_method_nonce` is provided.

[BraintreeBlue] Fix for partial updates with paypal account

---

lib/active_merchant/billing/gateways/cyber_source.rb
test/unit/gateways/cyber_source_test.rb

While https://github.com/activemerchant/active_merchant/pull/1875 introduces the `ipAddress` field, the whole method is only used for requests that send full payment profile data and not its tokenized form (see https://github.com/chargify/active_merchant/compare/master...chargify:pgt-740-cybersource-ip-addresses#diff-ec0894a572ca922f933a687ef23008524682ccea87eec57f3175e7e1c4013bb2R688).
According to the documentation, it should be possible to pass billing address data to the tokenized purchase request, though, as https://developer.cybersource.com/library/documentation/dev_guides/CC_Svcs_SO_API/Credit_Cards_SO_API.pdf, page 212 says:
_You can override most of the information associated with the customer token by including the relevant API fields in the payment or credit request. For …

CyberSource: Handle IP address field in tokenized purchase requests

---

lib/active_merchant/billing/gateways/braintree_blue.rb
test/remote/gateways/remote_braintree_blue_test.rb

This PR will add the possibility to do partial updates for credit cards if there is no full card number passed.

[Braintree] Add credit card partial update

---

lib/active_merchant/billing/gateways/blue_snap.rb

This will add fraud info when creating a subscription for the BlueSnap gateway.

[BlueSnap] Add fraud info when creating a subscription

---

lib/active_merchant/billing/gateways/stripe.rb
test/remote/gateways/remote_stripe_test.rb

This will add support for creating setup intents with customer_acceptance being set as offline.

[feature] Add support for offline customer_acceptance when creating setup_intents

---

lib/active_merchant/billing/gateways/nmi.rb
test/remote/gateways/remote_nmi_test.rb
test/unit/gateways/nmi_test.rb

This will add support for the statement descriptor in NMI.
**Summary for requirement:**
Merchants must add a descriptor that indicates a transaction related to a trial offer to the first transaction processed after the trial offer ends. This descriptor should be added to the Merchant Name field of the Clearing Record and should include language like “trial,” “trial period,” “free trial,” and the like. This will then appear on bank statements, banking apps, and text alerts that the cardholder sees.
**What is the enhanced descriptor for? Where is it required? ([Visa](https://usa.visa.com/dam/VCOM/global/support-legal/documents/subscription-policy-vbn-visa-public.pdf))**
The enhanced descriptor (e.g., “trial,” “trial period,” “free trial”) is to be included in the Merchant Name field of the …

[feature] Add statement descriptor for NMI

---

lib/active_merchant/billing/gateways/cyber_source.rb

In this PR I'm copying some logic from [the upstream AM](https://github.com/activemerchant/active_merchant/blob/3d7841d9c232a7ebed0c3f74cd4598576749030e/lib/active_merchant/billing/gateways/cyber_source.rb#L887) to fix issues with subsequentAuth payments.
Updating our AM so that it contains the same commits is a bigger task - there are more changes to the three ds fields as well as a SOAP schema change. I'd like to do that at a later time, once the current merchant issues are resolved.
I couldn't make all the tests pass locally but I can confirm these changes don't affect the test run, see screenshots before.
CyberSource remote tests before:
CyberSource remote tests now:
CyberSource unit tests now:

Update CyberSource subsequent auth logic

---

lib/active_merchant/billing/gateways/litle_new.rb
test/fixtures.yml
test/remote/gateways/remote_litle_new_certification_test.rb
test/remote/gateways/remote_litle_new_test.rb
test/unit/gateways/litle_new_test.rb

This will add Litle New Gateway with support for Stored Credentials.
This new gateway was extracted from this PR: https://github.com/chargify/active_merchant/pull/142
Co-authored-by: Jakub Mikrut <jakub.mikrut@chargify.com>

[Internal] Support for stored credentials for Litle gateway (as a new gateway)

---

lib/active_merchant/billing/gateways/blue_snap.rb
test/remote/gateways/remote_blue_snap_test.rb
test/unit/gateways/blue_snap_test.rb

This will fix creating a merchant-managed subscription in BlueSnap when a shopper has multiple credit cards.

[bugfix] Fix creating merchant-managed subscriptions in BlueSnap for a shopper with multiple cards

---

lib/active_merchant/billing/gateways/cyber_source.rb
test/unit/gateways/cyber_source_test.rb

Why?
https://chargify.atlassian.net/browse/PGT-1078
Some context: basically in case a transaction is made with Visa or MasterCard card and for some reason we don't have a networkTransactionId stored in our system we can skip the tag and CyberSource will try to find a networkTransactionId in their own system to fill the information in. The rep also told us that passing a blank tag prevents that behavior, that's why in this PR we're making a change from passing an empty networkTransactionId tag to not passing it at all.
What?
Avoid xml empty tag subsequentAuthTransactionID for cybersource

Avoid xml empty tag subsequentAuthTransactionID for cybersource

---

lib/active_merchant/billing/gateways/braintree_blue.rb
test/remote/gateways/remote_braintree_blue_test.rb

This will fix an error in the store method when payment_method_nonce was passed as an empty string

Braintree: fix a bug in the store method when payment_method_nonce was passed as empty string

---

activemerchant.gemspec

Current restrictions allow for 5.2.0 only.

Rails 5.2.x compatibility

---

lib/active_merchant/billing/gateways/digital_river.rb
test/unit/gateways/digital_river_test.rb

This will add support for passing order_failure_message to the ActiveMerchant's purchase method

[internal] Add ability to pass order failure message to ActiveMerchant 

---

Gemfile
lib/active_merchant/billing/gateways/digital_river.rb
test/remote/gateways/remote_digital_river_test.rb
test/unit/gateways/digital_river_test.rb

Jira: https://chargify.atlassian.net/jira/software/projects/PGT/boards/32?selectedIssue=PGT-1101
* Support refunds - both full and partial.
* DigitalRiver expects full amounts (e.g. 1.01 USD) not cents
* Remote tests utilize an order factory which looks for an existing order or creates a new one, which means it waits for the order's fulfillment for 60 seconds at most

Add Refunds support to DigitalRiver

---

lib/active_merchant/billing/gateways/digital_river.rb
test/remote/gateways/remote_digital_river_test.rb
test/unit/gateways/digital_river_test.rb

This PR adds an unstore action which wraps the detach_source endpoint for DigitalRiver gateway.
PR also adds one test case which was previously not possible to perform.

[DigitalRiver] Add unstore action

---

lib/active_merchant/billing/gateways/go_cardless.rb
test/unit/gateways/go_cardless_test.rb

Why?
https://chargify.atlassian.net/browse/PGT-1217
Payment profiles in gocardless (temporary customers) from chargify.js remain in gocardless gateway, although we can remove them.
What?
The following PR introduce changes in conduit layer required to fix the above issue:
- Add unstore to gocardless gateway
Related PR's:
- [conduit] https://github.com/chargify/conduit/pull/343
- [chargify] https://github.com/chargify/chargify/pull/19428

[bugfix] Add unstore and cancel mandate to gocardless gateway

---

Gemfile
lib/active_merchant/billing/gateways/digital_river.rb
test/unit/gateways/digital_river_test.rb

This will pass wiredump_device as the debug_option param to the DigitalRiver::Gateway

[internal] Add support for passing debug_output option to DigitalRiver::Gateway

---

lib/active_merchant/billing/gateways/digital_river.rb
test/unit/gateways/digital_river_test.rb

This PR fixes the way we fetch the source_id when performing a purchase. We exclude anything that is not a `creditCard`.

[DigitalRiver] Fix fetching source

---

lib/active_merchant/billing/gateways/digital_river.rb

This will increase the capture timeout limit from 2 to 5 seconds

[internal] increase the capture timeout limit from 2 to 5 seconds for Digital River

---

lib/active_merchant/billing/gateways/braintree_blue.rb

PGT-1660
chargify/chargify#20477
https://github.com/chargify/conduit/pull/368
Add payment_method_token to braintree_blue request params

[enhancement] add payment_method_token parameter for Braintree

---

lib/active_merchant/billing/gateways/adyen_checkout.rb
test/fixtures.yml
test/remote/gateways/remote_adyen_checkout_test.rb
test/unit/gateways/adyen_checkout_test.rb

Why?
Adyen live mode was not working
What?
To switch to production (live mode) url we need merchant specific url prefix, we set it in chargify and pass to AM
Conduit: https://github.com/chargify/conduit/pull/369
Chargify: https://github.com/chargify/chargify/pull/20625

[bugfix] Add live_url_prefix to live url

---

lib/active_merchant/billing/gateways/adyen_checkout.rb

Why?
During client testing we've found out that checkout directory is missing from live path
https://chargify.atlassian.net/browse/PGT-1695?focusedCommentId=29369
Chargify: https://github.com/chargify/chargify/pull/20644

Pgt 1695 fix adyen production url - add checkout directory to path

---

lib/active_merchant/billing/gateways/stripe.rb
test/fixtures.yml
test/remote/gateways/remote_stripe_test.rb

[PGT-2002](https://chargify.atlassian.net/browse/PGT-2002)
When merchant sets `invoice_settings[default_payment_method]` on customer Stripe object on his own, updating the card via SSP does not work, because credit card from  `invoice_settings[default_payment_method]` is preferred over `default_source`.
It sets `invoice_settings[default_payment_method]` together with `default_source`.
conduit: https://github.com/chargify/conduit/pull/380
chargify: https://github.com/chargify/chargify/pull/21296

[bugfix] fix updating default credit card on Stripe by updating also default_payment_method

---

lib/active_merchant/billing/gateways/forte.rb
lib/active_merchant/billing/gateways/stripe.rb
test/remote/gateways/remote_forte_test.rb
test/remote/gateways/remote_stripe_test.rb

[PGT-2093](https://chargify.atlassian.net/browse/PGT-2093)
- bank account number and routing number get scrubbed for ACH, SEPA direct debit, and BECS direct debit in logs from Stripe
- bank account number gets scrubbed for ACH from Forte gateway
Chargify: https://github.com/chargify/chargify/pull/21532
conduit: https://github.com/chargify/conduit/pull/385

[internal] scrub stripe bank account and routing number in gateway logs

---

Rakefile
activemerchant.gemspec

In order to upgrade Rails in the main Chargify app we need to bump the `activesupport` dependency version.

[internal] Bump Rails dependency version

---

lib/active_merchant/billing/gateways/payment_express.rb

[bugfix] improve scrubing invalid byte sequence before parsing xml response from Windcave

---

lib/active_merchant/billing/gateways/litle.rb

Why?
https://maxioevolution.atlassian.net/browse/PAYM-380
for one of our merchant, at the beginning it's under FF that sets up use_stored_cvn option
related work: https://github.com/maxio-com/chargify/pull/22674

Add cardValidationNum 000 for stored cvv for little

---

activemerchant.gemspec

https://maxioevolution.atlassian.net/browse/PAYM-267
`square.rb` gem in version prior to 7.0 is incompatible with Ruby 3.
`square.rb` gem has been bumped to version 7.0.

[internal] bump square.rb gem from 6.3 to 7.0

---

lib/active_merchant/billing/gateways/stripe.rb

**What:** 
- added 2 new Exceptions to StripeGateway
- changed to RunTimeError instead of StandardError, because there is some problem with conduit gem
This PR is related with:
https://github.com/maxio-com/chargify/pull/21872
And Jira Task:
https://chargify.atlassian.net/jira/software/c/projects/BQ/boards/86?modal=detail&selectedIssue=BQ-991&assignee=62d8043596f239ca6ae81ede

[internal] added exceptions  StripeCustomerManyPaymentMethodWithoutDefault and StripeCustomerDoesNotExist

---

lib/active_merchant/billing/gateways/payment_express.rb

Ticket: [PAYM-616](https://maxioevolution.atlassian.net/browse/PAYM-616)
Update windcave test and live urls
Since the end of June our [external specs](https://buildkite.com/chargify-ci/chargify-main-app/builds/95309#_) for windcave started to fail due to the missing domain - `connection to the remote server could not be established`
```
$ nslookup uat.paymentexpress.com
Server:		2001:730:3ed2:1000::53
Address:	2001:730:3ed2:1000::53#53
** server can't find uat.paymentexpress.com: NXDOMAIN
```
It appears that Windcave updated their UAT domain on June 28, 2023, causing merchants using our integration with Windcave on their test sites to encounter transaction failures starting on that date. 
Windcave provided PDF to their merchants notifying them about IP addresses change in case of any …

[bugfix] update windcave domain

---

lib/active_merchant/billing/gateways/blue_snap.rb

Include 3ds ref info for store action
For UK it is mandatory to include such info in store action, banks may reject request otherwise
https://github.com/maxio-com/chargify/pull/23163
Ticket: [PAYM-553](https://maxioevolution.atlassian.net/browse/PAYM-553)
[PAYM-553]: https://maxioevolution.atlassian.net/browse/PAYM-553?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[bugfix] Include 3ds info for store action

---

lib/active_merchant/billing/gateways/paypal_complete.rb

Ticket: [PAYM-777](https://maxioevolution.atlassian.net/browse/PAYM-777)
Add fraudnet header when `correlation_id` is being passed
To have additional fraud protection on paypal layer
[PAYM-777]: https://maxioevolution.atlassian.net/browse/PAYM-777?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[feature] Add fraudnet header if correlation_id present

---

lib/active_merchant/billing/gateways/paypal_complete.rb

Include experiance context in order api call
To serve better experience for buyers through PayPal gateway
Ticket: [PAYM-1033](https://maxioevolution.atlassian.net/browse/PAYM-1033)
[PAYM-1033]: https://maxioevolution.atlassian.net/browse/PAYM-1033?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[feature] Add experience context to orders api call

---

lib/active_merchant/billing/gateways/paypal_complete.rb

- It adds the SCA indicators for triggering Paypal's RTAU
[PAYM-1558]: https://maxioevolution.atlassian.net/browse/PAYM-1558?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

add sca info when using credit card for paypal rtau

---

README.md
lib/active_merchant/billing/gateways/pin.rb
test/remote/gateways/remote_pin_test.rb
test/unit/gateways/pin_test.rb

Ticket:
https://maxioevolution.atlassian.net/browse/PAYM-1925
What
Pin gateway API domain was changed from `api.pin.net.au` to `api.pinpayments.com`
Why
Pin Payments is sunsetting their API domain of [api.pin.net.au](http://api.pin.net.au/) in replacement of [api.pinpayments.com](http://api.pinpayments.com/)
How
The values were updated In the payment's config and related tests were refactored accordingly

[internal] change Pin gateway  API domain

---

lib/active_merchant/billing/gateways/litle.rb

Ticket:
https://maxioevolution.atlassian.net/browse/PAYM-1935
What
A new approved response code was added. It is exclusively for Mastercard
Why
WorldPay (former Vantiv, former Litle) added a new approved code for Mastercard multi-use virtual card
How
Adding this new code in the `success_from` method
Note
- I couldn't add a test because the unit test for the litle gateway fails even before this change

[bugfix] Add Mastercard multi-use virtual card approved code for Litle->Vantiv->WorldPay

---

activemerchant.gemspec

Ticket: https://maxioevolution.atlassian.net/browse/PAYM-1881
Bump square gem version
To have access to Cards API and card resource in current responses

[internal] Bump square gem to have access to card API

---

lib/active_merchant/billing/gateways/paypal_complete.rb
test/unit/gateways/pay_pal_complete_test.rb

Ticket: https://maxioevolution.atlassian.net/browse/PAYM-1934
Check against capture status in PPCP purchase
It is possible that order request will return positive status but capture nested inside has failure. That leads to false positive purchases on AB side.

[bugfix] Check against capture status in PPCP purchase

---

lib/active_merchant/billing/gateways/paypal_complete.rb

Ticket: https://maxioevolution.atlassian.net/browse/PAYM-1986
Raise error only upon 5xx HTTP statuses
As for 4xx follow common structure where we can parse out valueable info

[bugfix] Raise error only upon 5xx HTTP statuses

---

lib/active_merchant/billing/gateways/cyber_source.rb
lib/active_merchant/version.rb
test/fixtures.yml
test/test_helper.rb
test/unit/gateways/cyber_source_test.rb

Ticket:
https://maxioevolution.atlassian.net/browse/PAYM-1989
What
- We need to handle the new auth flow using a p12 certificate when using the Cybersource gateway. We must keep the old flow too.
Why
- Cybersource is changing their auth method to using a p12 certificate to sign every request based on its payload, so we need to add this
How
- The gateway initializer can now receive 2 new attributes: `p_12` (the certificate contents) and `p12_password` (the password to decrypt it)
- A new flow is added when creating the payload to be sent to the SOAP API
- The Cybersource gateway class now supports login and password auth and the new p12 cert auth flow.
- This implementation mimics Cybersource's [official PHP toolkit](https://github.com/CyberSource/cybersource-soap-toolkit/blob/master/PHPSoa …

[feature] Paym 1989 gateway cybersource soap api authentication update

---

activemerchant.gemspec

Ticket:
[PAY-2151](https://maxioevolution.atlassian.net/browse/PAY-2151)
What
We need to mode the `rexml` dependency from `Payments` to this fork.
Why
To decrease the dependencies on our apps
How
Adding the dependency to this project and move it from `Payments` and `Chargify`
- The dependencies were updated in `Chargify`, `Payments` and `ActiveMerchant`.
- Payments: https://github.com/maxio-com/payments/pull/303
- ActiveMerchant: https://github.com/maxio-com/active_merchant/pull/238
- Chargify: https://github.com/maxio-com/chargify/pull/25507
[PAY-2151]: https://maxioevolution.atlassian.net/browse/PAY-2151?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Internal] add rexml as a dependency

---

Gemfile
lib/active_merchant/billing/gateways/braintree_blue.rb

Ticket: https://maxioevolution.atlassian.net/browse/PAY-2069
Bump braintree gem version
From June 30, 2025 previous version won't be compatible with their API
https://github.com/maxio-com/conduit/pull/443
https://github.com/maxio-com/chargify/pull/25884

[internal] Bump Braintree gem version
