maxio-com/active_merchant

- lib/active_merchant/billing/gateways/fusebox.rb
- test/fixtures.yml
- test/remote/gateways/remote_fusebox_test.rb
- test/unit/gateways/fusebox_test.rb
> Add Elavon Fusebox gateway

- README.md
- lib/active_merchant/billing/gateways/cyber_source.rb
This adds South Africa support to Cybersource.
> Adds South Africa support to Cybersource

- lib/active_merchant/billing/gateways/elavon.rb
- test/fixtures.yml
- test/remote/gateways/remote_elavon_test.rb
See: https://github.com/activemerchant/active_merchant/pull/2608/files
> [patch] Updates Elavon URLs

- lib/active_merchant/billing/check.rb
- lib/active_merchant/billing/gateways/go_cardless.rb
- test/fixtures.yml
- test/remote/gateways/remote_go_cardless_test.rb
- test/unit/check_test.rb
- test/unit/gateways/go_cardless_test.rb
This PR adds support for GoCardless gateway.
co-authors: @himn1, @JakubKopys
> [feature] adds GoCardless gateway

- lib/active_merchant/billing/gateways/go_cardless.rb
- test/fixtures.yml
- test/remote/gateways/remote_go_cardless_test.rb
- test/unit/gateways/go_cardless_test.rb
This PR adds support for refunds in GoCardless gateway
> [feature] adds Gocardless refunds

- lib/active_merchant/billing/gateways/litle.rb
- test/remote/gateways/remote_litle_test.rb
- test/unit/gateways/litle_test.rb
Adds ability to log Raw Log Contents in Raw Gateway Log.
> Vantiv (Litle): Add scrubbing

- lib/active_merchant/billing/gateways/stripe.rb
- test/unit/gateways/stripe_test.rb
This PR fixes bug when payment intents API is used with ach payment.
> Stripe: Fix bug with ach and payment intents API

- lib/active_merchant/billing/gateways/stripe.rb
- test/unit/gateways/stripe_test.rb
This fixes some bugs related to Stripe 3D secure.
> Stripe: fix some bugs related to Stripe 3D secure.

- lib/active_merchant/billing/gateways/adyen_checkout.rb
- test/fixtures.yml
- test/unit/gateways/adyen_checkout_test.rb
This adds support for Adyen 3DS
```
Loaded suite test/remote/gateways/remote_adyen_checkout_test
Started
..................
Finished in 7.349448 seconds.
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
18 tests, 50 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
```
```
Loaded suite test/unit/gateways/adyen_checkout_test
Started
...............
Finished in 0.063384 seconds.
-------------------------------------------------------------------------- …
```
> [feature] Adyen 3DS support

- lib/active_merchant/billing/gateways/forte.rb
- change urls and headers
- remove unused check_number
- change action from disburse to credit
See activemerchant/active_merchant PR 3642
> Update to Forte api v3

- lib/active_merchant/billing/gateways/forte.rb
- test/remote/gateways/remote_forte_test.rb
This will add support for ACH payments using Forte gateway
Jira: [PGT-275](https://chargify.atlassian.net/browse/PGT-275)
> [feature] Add support for ACH in Forte gateway

- lib/active_merchant/billing/gateways/stripe.rb
https://chargify.atlassian.net/browse/PGT-142
A merchant may have disconnected from their gateway “Stripe” or API creds have become bad.
After refund merchant see:
catch and show error:
1. Create a statement site with Stripe gateway.
2. Create a plan.
3. Create a subscription.
4. Change  gateway creds in rails console:
```ruby 
s = SiteGatewaySetting.find_by(site_id: <site id>)
s.credentials[:access_token] = "wrong_token"
s.save!
```
5. Open created subscription.
6. Subscription Action -> Process Refund -> Process Refund Button
7. Notification with Error `Invalid API Key provided ...`
> [bugfix] Stripe refund - catch error if gateway is disconnected

- lib/active_merchant/billing/gateways/paypal_commerce_platform.rb
- test/fixtures.yml
- test/remote/gateways/remote_paypal_commerce_platform_test.rb
- test/unit/gateways/pay_pal_commerce_platform_test.rb
This will add support for PayPal Commerce Platform
Jira: [PGT-419](https://chargify.atlassian.net/browse/PGT-419)
> [feature] Add PayPal Commerce Platform gateway

- lib/active_merchant/billing/gateways/blue_snap.rb
- test/remote/gateways/remote_blue_snap_test.rb
- test/unit/gateways/blue_snap_test.rb
This updates the BlueSnap gateway to the latest from upstream ActiveMerchant master as of 812c28c.
lib/active_merchant/billing/gateways/blue_snap.rb at 3b7a6b6
test/remote/gateways/remote_blue_snap_test.rb at a13df07
test/unit/gateways/blue_snap_test.rb at at a13df07
> BlueSnap: Update to latest gateway implementation

- Gemfile
- lib/active_merchant/billing/gateways/blue_snap.rb
- test/remote/gateways/remote_blue_snap_test.rb
- test/test_helper.rb
- test/unit/gateways/blue_snap_test.rb
This PR extracts the create_subscription method for BlueSnap, enabling to use it on itself.
> [internal] Extract create subscription method

- lib/active_merchant/billing/gateways/unipaas.rb
- test/fixtures.yml
- test/remote/remote_unipaas_test.rb
- test/unit/gateways/unipaas_test.rb
Add support for UNIPaaS Gateway.
The library has prepared by Unipaas: [whatlight/active_merchant](https://github.com/whatlight/active_merchant/blob/master/lib/active_merchant/billing/gateways/unipaas.rb)
Other PR's:
https://github.com/chargify/chargify/pull/17865
https://github.com/chargify/conduit/pull/307
> [Feature] UniPaaS Gateway integration GA

- lib/active_merchant/billing/gateways/unipaas.rb
- test/remote/remote_unipaas_test.rb
UNIPaaS - Support for recurring transaction ID
> [Feature] UNIPaaS - Support for recurring transaction ID

- lib/active_merchant/billing/gateways/forte.rb
- test/remote/gateways/remote_forte_test.rb
This will change the default sec_code from WEB to PPD
> [Forte] Change default sec_code for Forte

- lib/active_merchant/billing/gateways/litle.rb
- test/fixtures.yml
- test/remote/gateways/remote_litle_certification_test.rb
- test/remote/gateways/remote_litle_test.rb
- test/unit/gateways/litle_test.rb
Update AM for Litle gateway.
Update Litle API version.
Support for stored credentials for Litle gateway.
> [Internal] Support for stored credentials for Litle gateway

- lib/active_merchant/billing/gateways/litle.rb
- test/fixtures.yml
- test/remote/gateways/remote_litle_certification_test.rb
- test/remote/gateways/remote_litle_test.rb
- test/unit/gateways/litle_test.rb
Reverts chargify/active_merchant#142
> Revert "[Internal] Support for stored credentials for Litle gateway"

- lib/active_merchant/billing/gateways/stripe.rb
- test/remote/gateways/remote_stripe_test.rb
This will add support for SEPA Direct Debit payments for Stripe gateway
> [feature] Add support for SEPA direct debit in store and purchase with Stripe

- lib/active_merchant/billing/gateways/stripe.rb
- test/remote/gateways/remote_stripe_test.rb
This will support for store another SEPA direct debit payment method for an existing customer.
> [feature] Add support for store another SEPA direct debit for existing customer with Stripe 

- lib/active_merchant/billing/gateways/blue_snap.rb
- test/remote/gateways/remote_blue_snap_test.rb
Blue Snap: support for 3D Secure.
> [feature] Blue Snap 3DS

- lib/active_merchant/billing/gateways/stripe.rb
- test/remote/gateways/remote_stripe_test.rb
This will add support for BECS Direct Debit payments for Stripe gateway
> [feature] Add support for BECS direct debit in store and purchase with Stripe

- lib/active_merchant/billing/gateways/square.rb
- test/fixtures.yml
- test/remote/gateways/remote_square_test.rb
- test/unit/gateways/square_test.rb
This will rename SquareNew to Square
> [Internal] Clean up square new

- Gemfile
- lib/active_merchant/billing/gateways/digital_river.rb
- test/fixtures.yml
- test/remote/gateways/remote_digital_river_test.rb
- test/unit/gateways/digital_river_test.rb
This PR adds updates to handle the most recent changes to the DigitalRiver API and updates to the digital_river gem version that handles the new API.
> [DigitalRiver] Update to newest DR API version changes

- lib/active_merchant/billing/gateways/digital_river.rb
- test/remote/gateways/remote_digital_river_test.rb
- test/unit/gateways/digital_river_test.rb
This PR add handling of the `success_pending_order` option in purchase.
> [DigitalRiver] handle success_pending_order option in purchase

- lib/active_merchant/billing/gateways/checkout_v2.rb
- test/fixtures.yml
- test/remote/gateways/remote_checkout_v2_test.rb
- test/unit/gateways/checkout_v2_test.rb
This will add support for the Checkout.com gateway.
> Add store method for CheckoutV2 gateway

- lib/active_merchant/billing/gateways/checkout_v2.rb
- test/fixtures.yml
- test/remote/gateways/remote_checkout_v2_test.rb
- test/unit/gateways/checkout_v2_test.rb
This will do a card verification during tokenizing in the Checkout.com gateway
> Do a card verification during tokenizing in the Checkout.com gateway

- lib/active_merchant/billing/gateways/checkout_v2.rb
- test/remote/gateways/remote_checkout_v2_test.rb
This PR will add support for updating card and customer details.
> Add support for Checkout card and customer details.

- lib/active_merchant/billing/gateways/checkout_v2.rb
- test/remote/gateways/remote_checkout_v2_test.rb
- test/unit/gateways/checkout_v2_test.rb
This will add support for stored credentials for the checkout.com gateway
> Add support for stored credentials for the checkout.com gateway

- lib/active_merchant/billing/gateways/checkout_v2.rb
This PR will add support for customer email change for the partial update.
> [bugfix] Support for customer email change for partial update

- lib/active_merchant/billing/gateways/checkout_v2.rb
- test/remote/gateways/remote_checkout_v2_test.rb
- test/unit/gateways/checkout_v2_test.rb
This will add support for 3DS during card tokenization
> [feature] Add support for 3DS during card tokenization

- lib/active_merchant/billing/gateways/blue_snap.rb
- test/fixtures.yml
- test/remote/gateways/remote_blue_snap_test.rb
- test/unit/gateways/blue_snap_test.rb
why?
It is needed for one of the migrations
https://chargify.atlassian.net/browse/PGT-1258
PRs:
Conduit: https://github.com/chargify/conduit/pull/359
Ch: https://github.com/chargify/chargify/pull/19853
> [internal] Add retrieve action to bluesnap gw

- lib/active_merchant/billing/gateways/go_cardless.rb
- test/unit/gateways/go_cardless_test.rb
This will add support for scrubbing for the GoCardless gateway
> [internal] add scrubbing for GoCardless

- lib/active_merchant/billing/gateways/square.rb
- test/unit/gateways/square_test.rb
After this PR, the transcript will be scrubbed from the full card number and verification_value for Square gateway.
Tests:
> Scrub full card numbers for square

- lib/active_merchant/billing/gateways/eway.rb
> [internal] Pgt 2325 eway - add more scrubbing

- lib/active_merchant/billing/gateways/braintree_blue.rb
This PR will allow using `payment_method_nonce` while updating a card for the Customer.
> Support payment_method_nonce in card update

- lib/active_merchant/billing/gateways/stripe.rb
raise StripeCustomerDoesNotExist if message matched this exception
> [bugfix]  raise StripeCustomerDoesNotExist if message matched this exception

- lib/active_merchant/billing/gateways/stripe.rb
This is related with task:
https://maxioevolution.atlassian.net/browse/IN-80
After last change, we have got a error with test RateLimtError.
In the fulture this code should be refactored to more specific error.
Now builds to confirm working solution:
- conduit: https://github.com/maxio-com/conduit/pull/416 (with this branch)
- chargify: https://github.com/maxio-com/chargify/pull/22921 ( with this branch, and conduit branch)
> [bugfix] changed stripe customer_payment_methods, added new RuntimeError

- lib/active_merchant/billing/gateways/stripe.rb
https://maxioevolution.atlassian.net/browse/PAYM-840
Add prevention mechanism for level 3 data to escape it upon the error and notify HB
It's hard to predict what can happen with level 3 data due to the multiple complex setting of the product. With release of level 3 data we don't want merchants to encounter errors anymore
> [internal] Escape level 3 data upon error and notify HB

- activemerchant.gemspec
- lib/active_merchant.rb
- lib/active_merchant/billing/gateways/paypal_complete.rb
- test/fixtures.yml
- test/remote/gateways/remote_pay_pal_complete_test.rb
- test/unit/gateways/pay_pal_complete_test.rb
[PAYM-890](https://maxioevolution.atlassian.net/browse/PAYM-890)
Add integration for PayPal Complete Payments gateway to serve PPCP services 
[PAYM-890]: https://maxioevolution.atlassian.net/browse/PAYM-890?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [feature] PayPal Complete gateway integration

- lib/active_merchant/billing/check.rb
- test/unit/check_test.rb
Update billing check for Canada routing numbers. It was suggested in: https://maxioevolution.atlassian.net/browse/PAYM-997
> Update billing check for Canada routing numbers handling

- lib/active_merchant/billing/gateways/paypal_complete.rb
Ticket: [PAYM-1024](https://maxioevolution.atlassian.net/browse/PAYM-1024)
- add possibility to generate vault token from paypal nonce
- submit different types of payment sources on purchase
To handle paypal button scenario
[PAYM-1024]: https://maxioevolution.atlassian.net/browse/PAYM-1024?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [feature] Add handling for parameters for paypal button flow 

- lib/active_merchant/billing/gateways/paypal_complete.rb
Fix vaulting of credit card for paypal
> [bugfix] Fix paypal vaulting

- lib/active_merchant/billing/gateways/paypal_complete.rb
Fix how we are checking if paypal nonce is present
> [bugfix] Fix paypal nonce handling

- lib/active_merchant/billing/gateways/paypal_complete.rb
Add level 2 and 3 data for PayPal Complete Payments gateway
To pass certification and increase our revenue
Ticket: [PAYM-1035](https://maxioevolution.atlassian.net/browse/PAYM-1035)
[PAYM-1035]: https://maxioevolution.atlassian.net/browse/PAYM-1035?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [feature] Add level 2 and 3 data for PayPal Complete

- lib/active_merchant/billing/gateways/stripe.rb
- test/remote/gateways/remote_stripe_test.rb
This PR will add support for Stripe BACS payments.
> [feature] Stripe BACS support

- lib/active_merchant/billing/gateways/go_cardless.rb
- test/unit/gateways/go_cardless_test.rb
Ticket: [PAYM-837](https://maxioevolution.atlassian.net/browse/PAYM-837)
[PAYM-837]: https://maxioevolution.atlassian.net/browse/PAYM-837?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [feature] GoCardless ACH integration

- lib/active_merchant/billing/gateways/paypal_complete.rb
https://maxioevolution.atlassian.net/browse/PAYM-2011
Fix setup of payment source for PayPal account payment method
As it has been broken within - https://github.com/maxio-com/active_merchant/pull/229
> [bugfix] Fix setup of payment source for PayPal account
